function [p1, v1, a1, p2, v2, a2] = traffic_manager(traffic_params, spawn_range, vehicule_step, nb_vehicules, nb_samples, dt)
    % TRAFFIC_MANAGER - Manages traffic simulation for two lanes.
    %
    % Parameters:
    %   traffic_params (struct): Traffic configuration parameters.
    %   spawn_range (cell array): Spawn ranges for each lane.
    %   vehicule_step (array): Step size for vehicle positions in each lane.
    %   nb_vehicules (array): Number of vehicles in each lane.
    %   nb_samples (int): Number of simulation samples.
    %   dt (float): Time step for the simulation.
    %
    % Returns:
    %   p1, v1, a1 (arrays): Position, velocity, and acceleration for lane 1.
    %   p2, v2, a2 (arrays): Position, velocity, and acceleration for lane 2.

    % Simulate traffic for lane 1
    [p1, v1, a1] = lane_manager( ...
        traffic_params, ...
        spawn_range{1}, ...
        vehicule_step(1), ...
        nb_vehicules(1), ...
        nb_samples ...
    );

    % Simulate traffic for lane 2
    [p2, v2, a2] = lane_manager( ...
        traffic_params, ...
        spawn_range{2}, ...
        vehicule_step(2), ...
        nb_vehicules(2), ...
        nb_samples ...
    );
end