function channel = create_channel(delay, attenuation, doppler_shift, K, conf)
    max_doppler = max(abs(doppler_shift));
    los_f_d = doppler_shift(end); % On suppose que c'est le chemin LOS
    los_phase = 2 * pi * rand();  % Un seul chemin direct → phase unique

    channel = comm.RicianChannel( ...
        SampleRate = conf.emitter.params.fs, ...
        PathDelays = delay, ...
        AveragePathGains = attenuation, ...
        DirectPathDopplerShift = los_f_d, ...
        KFactor = K(end), ...
        DirectPathInitialPhase = los_phase, ...
        MaximumDopplerShift = max_doppler, ...
        ChannelFiltering = true, ...
        Visualization = 'Off');
end
